routes/web.php
    // Password Reset Routes...

    Route::get('password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('administrator.password.request');
    Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('administrator.password.email');
    Route::get('password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('administrator.password.reset.token');
    Route::post('password/reset', 'Admin\Auth\ResetPasswordController@reset');

});
Route::group(['prefix' => 'administrator','namespace' => 'Admin', 'middleware' => ['admin']], function () {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('admin.home');

    Route::resource('helpAdmin', 'HelpAdminController');
    Route::get('helpAdmin/{id}/delete', 'HelpAdminController@delete')->name('helpAdmin.delete');
    Route::post('helpAdmin/{id}/delete', 'HelpAdminController@deleteHelpAdmin')->name('helpAdmin.message.delete');
    Route::post('helpAdmin/{id}/suspend', 'HelpAdminController@suspendHelpAdmin')->name('helpAdmin.message.suspend');
    Route::get('user/{id}/delete', 'UsersController@delete')->name('user.for.delete');
    Route::post('user/suspend', 'HelpAdminController@suspend')->name('user.suspend');
    // Roles routes ..........
    Route::resource('roles', 'RolesController');
    Route::post('role/delete', 'RolesController@delete')->name('role.delete');

    Route::resource('users', 'UsersController');
    Route::post('refuseUser','UsersController@refuseUser')->name('user.refuseUser');
    Route::post('reAcceptUser','UsersController@reAcceptUser')->name('user.reAcceptUser');
    Route::post('accepted','UsersController@accpetedUser')->name('user.accepted');
    Route::post('suspendUser','UsersController@suspendUser')->name('user.suspendUser');

    Route::resource('deliveries', 'DeliveryController');
    Route::post('deliveries/accepted','DeliveryController@accpetedUser')->name('deliveries.accepted');
    Route::post('deliveries/refuseUser','DeliveryController@refuseUser')->name('deliveries.refuseUser');

    Route::resource('agents', 'AgentController');

    Route::resource('cities', 'CitiesController');
    Route::post('cities/delete', 'CitiesController@delete')->name('cities.delete');
    Route::post('city/suspend', 'CitiesController@suspend')->name('city.suspend');

    // -------------------------------------- products .................
    Route::resource('products', 'ProductController');
    Route::post('products/delete', 'ProductController@delete')->name('products.delete');
    Route::post('products/suspend', 'ProductController@suspend')->name('products.suspend');

    // -------------------------------------- agent products .................
    Route::resource('agent_products', 'AgentProductController');
    Route::post('agent_products/delete', 'AgentProductController@delete')->name('agent_products.delete');
    Route::post('agent_products/suspend', 'AgentProductController@suspend')->name('agent_products.suspend');
    Route::post('agent_products/renderProductData', 'AgentProductController@renderProductData')->name('agent_products.renderProductData');

    // -------------------------------------- agent products Offers .................
    Route::resource('agent_product_offer', 'AgentProductOfferController');
    Route::post('agent_product_offer/delete', 'AgentProductOfferController@delete')->name('agent_product_offer.delete');
    Route::post('agent_product_offer/suspend', 'AgentProductOfferController@suspend')->name('agent_product_offer.suspend');

    // -------------------------------------- offer products .................
    Route::resource('offer_products', 'OfferProductController');
    Route::post('offer_products/delete', 'OfferProductController@delete')->name('offer_products.delete');
    Route::post('offer_products/suspend', 'OfferProductController@suspend')->name('offer_products.suspend');

    // --------------------------------------  promo_codes .................
    Route::resource('promo_codes', 'PromoCodesController');
    Route::post('promo_codes/delete', 'PromoCodesController@delete')->name('promo_codes.delete');
    Route::post('promo_codes/suspend', 'PromoCodesController@suspend')->name('promo_codes.suspend');

    // -------------------------------------- categories .................
    Route::resource('categories', 'CategoriesController');
    Route::post('categories/delete', 'CategoriesController@delete')->name('categories.delete');
    Route::post('categories/suspend', 'CategoriesController@suspend')->name('categories.suspend');

    // -------------------------------------- cars .................
    Route::resource('cars', 'CarController');
    Route::post('cars/delete', 'CarController@delete')->name('cars.delete');
    Route::post('cars/suspend', 'CarController@suspend')->name('cars.suspend');

    // -------------------------------------- brands .................
    Route::resource('brands', 'BrandController');
    Route::post('brands/delete', 'BrandController@delete')->name('brands.delete');
    Route::post('brands/suspend', 'BrandController@suspend')->name('brands.suspend');

    // -------------------------------------- charity_addresses .................
    Route::resource('charity_addresses', 'CharityAddressController');
    Route::post('charity_addresses/delete', 'CharityAddressController@delete')->name('charity_addresses.delete');
    Route::post('charity_addresses/suspend', 'CharityAddressController@suspend')->name('charity_addresses.suspend');

    // -------------------------------------- notifications_admin .................
    Route::resource('notifications_admin', 'NotificationController');
    Route::get('notifications/promo_code', 'NotificationController@promo_code')->name('notifications_admin.promo_code');
    Route::get('notifications/get_promo_code', 'NotificationController@get_promo_code')->name('notifications_admin.get_promo_code');
    Route::get('notifications/renderUsesData', 'NotificationController@renderUsesData')->name('notifications_admin.renderUsesData');
    Route::post('notifications_admin/send_promo_code', 'NotificationController@send_promo_code')->name('notifications_admin.send_promo_code');
    Route::post('notifications_admin/delete', 'NotificationController@delete')->name('notifications_admin.delete');

    Route::get('settings/contacts', 'SettingsController@contactus')->name('settings.contactus');
    Route::get('settings/orderPricing', 'SettingsController@orderPricing')->name('settings.order.pricing');
    Route::get('settings/aboutus', 'SettingsController@aboutus')->name('settings.aboutus');
    Route::get('settings/terms', 'SettingsController@terms')->name('settings.terms');
    Route::get('settings/termsProvider', 'SettingsController@termsGym')->name('settings.termsGym');
    Route::get('settings/termsDelivery', 'SettingsController@termsDelivery')->name('settings.termsDelivery');

    Route::post('/settings', 'SettingsController@store')->name('administrator.settings.store');
    Route::post('/settings/packageStore', 'SettingsController@packageStore')->name('administrator.package.store');


    Route::resource('banks', 'BanksController');
    Route::post('bank/suspend', 'BanksController@suspend')->name('bank.suspend');

    Route::get('bank-transfer-admin', 'BankTransferController@index')->name('bank-transfer-admin');
    Route::post('accept-transfer-admin', 'BankTransferController@accepted')->name('accept-transfer-admin');
    Route::post('refuse-transfer-admin', 'BankTransferController@refuse')->name('refuse-transfer-admin');

    Route::get('subscriptions-dealers', 'SubscriptionController@index')->name('subscriptions-dealers');
    Route::post('subscriptions-dealers', 'SubscriptionController@accepted')->name('accept-subscriptions-dealers');


    Route::resource('contact_us_inbox', 'ContactUsController');
    Route::get('updateIsRead', 'ContactUsController@updateIsRead')->name('admin.support.updateIsRead');
    Route::get('updateIsDeleted', 'ContactUsController@updateIsDeleted')->name('admin.support.updateIsDeleted');
    Route::get('removeAllMessages', 'ContactUsController@removeAllMessages')->name('admin.support.removeAllMessages');


    Route::get('invoices_orders','ReportsController@invoices_orders')->name("admin.invoices_orders");
    Route::get('invoices_orders_show/{user}','ReportsController@invoices_orders_show')->name("admin.invoices_orders_show");
    Route::get('invoices_orders_excel/{user}','ReportsController@invoices_orders_excel')->name("admin.invoices_orders_excel");
    Route::post('/logout', 'LoginController@logout')->name('administrator.logout');

});



Route::get('/sub', function (Illuminate\Http\Request $request) {

    $cities =\App\Models\City::whereParentId($request->id)->get();

    if (!empty($cities) && count($cities) > 0){
        return response()->json( $cities);
    }else{

        return response()->json(401);
    }


})->name('getSub');



Route::get('roles', function () {

    $user = auth()->user();
//    $user->retract('admin');
    $user->assign('*');
    Bouncer::allow('*')->everything();
    $user->allow('users_manage');
});


Route::post('user/update/token', function (Illuminate\Http\Request $request) {

    $user = \App\User::whereId($request->id)->first();


    if ($request->token) {
        $data = \App\Models\Device::where('device', $request->token)->first();
        if ($data) {
            $data->user_id = $user->id;
            $data->save();
        } else {


            $data = new \App\Models\Device;
            $data->device = $request->token;
            $data->user_id = $user->id;
            $data->device_type = 'web';
            $data->save();
        }
    }


})->name('user.update.token');


Route::get('test_image',function (){

    $user = \App\User::with('profile.media')->find(5);

    $image = $user->profile->getMedia('default', ['image' => 'profile']);

app/Http/Controllers/Admin/AgentProductOfferController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Agent\StoreOfferProduct;
use App\Models\Offer;
use App\Models\Product;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class AgentProductOfferController extends Controller
{
    public function index(Request  $request){

        $user = Auth::user();

        $offers = Offer::join('user_product','offers.product_id','=','user_product.product_id')
            ->join('products','offers.product_id','=','products.id')
            ->select('offers.id','offers.user_id','offers.price as offer_price','offers.start_at','offers.end_at','offers.is_suspend'
                ,'user_product.price as product_price', 'products.name_ar',
                DB::raw('round( ( offers.price /user_product.price * 100 ),2) as percentage'))
            ->where('offers.end_at','>=',Carbon::now())->where('user_product.user_id','=',$user->id)
            ->where('offers.user_id','=',$user->id)->get();

        $pageName = 'العروض';

        return view('admin.agent_product_offers.index',compact('offers','pageName'));
    }


    public function create(){

        $user = Auth::user();

        $products = $user->products->where('is_suspend',0)->where('is_deleted',0)
            ->where('pivot.is_suspend',0)->where('pivot.is_deleted',0);

        if ($products->count() == 0){
            session()->flash('myErrors','للاسف لا يوجد منتجات حالية للإضافة تواصل مع الإدارة');
            return  redirect()->back();
        }

        return view('admin.agent_product_offers.create',compact('products'));
    }


    public function store(StoreOfferProduct  $request){

        $user = Auth::user();

        offer::updateOrCreate(['user_id' => $user->id,'product_id' => $request->product_id],$request->validated());

        return response()->json([
            'status' => true,
            "message" => __('trans.addingSuccess',['itemName' => 'المنتج']),
            "url" => route('agent_products.index'),
        ]);
    }

    public function edit($id){
        $user = Auth::user();

        $products = $user->products->where('is_suspend',0)->where('is_deleted',0)
            ->where('pivot.is_suspend',0)->where('pivot.is_deleted',0);

        if ($products->count() == 0){
            session()->flash('myErrors','للاسف لا يوجد منتجات حالية للإضافة تواصل مع الإدارة');
            return  redirect()->back();
        }

        $offer = Offer::findOrFail($id);

        return view('admin.agent_product_offers.edit',compact('products','offer'));
    }

    public function update(StoreOfferProduct  $request){

        $user = Auth::user();

        offer::updateOrCreate(['user_id' => $user->id,'product_id' => $request->product_id],$request->validated());

        return response()->json([
            'status' => true,
            "message" => __('trans.editSuccess',['itemName' => "المنتج"]),
            "url" => route('agent_product_offer.index'),
        ]);
    }


    public function suspend(Request $request)
    {
        $model = Offer::findOrFail($request->id);
        $model->is_suspend = $request->type;
        if ($request->type == 1) {
            $message = "لقد تم حظر العرض بنجاح";
        } else {
            $message = "لقد تم فك الحظر على العرض بنجاح";
        }
        $model->save();
        return response()->json([
            'status' => true,
            'message' => $message,
            'id' => $request->id,
            'type' => $request->type

        ]);

    }
}

resources/views/admin/agent_product_offers/create.blade.php
@extends('admin.layouts.master')
@section('title' , 'إضافة مستخدم')

@section('styles')
    <style>

        .hidden-category{
            visibility: hidden !important;
        }


    </style>
@endsection
@section('content')
    <form id="myForm" method="POST" action="{{ route('agent_product_offer.store') }}" enctype="multipart/form-data" data-parsley-validate
          novalidate>
    {{ csrf_field() }}

    <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="btn-group pull-right m-t-15">
                    <button type="button" class="btn btn-custom  waves-effect waves-light"
                            onclick="window.history.back();return false;"> رجوع <span class="m-l-5"><i
                                    class="fa fa-reply"></i></span>
                    </button>
                </div>
                <h4 class="page-title">إدارة المنتجات</h4>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-8">
                <div class="card-box">
                    <h4 class="header-title m-t-0 m-b-30">إضافة منتج</h4>

                    <div class="col-xs-6">
                        <div class="form-group ">
                            <label for="passWord2">المنتج *</label>
                            <select   class="form-control  product_change"  name="product_id"
                                      required  data-parsley-required-message="من فضلك اختار المنتج"  >
                                <option value="" disabled selected hidden class="text-white">إختر </option>
                                @foreach($products as  $value)
                                    <option value="{{ $value->id }}" >{{ $value->name_ar }} - السعر  {{$value->pivot->price}} $</option>
                                @endforeach

                            </select>
                        </div>
                    </div>


                    <div class="col-xs-6">
                        <div class="form-group">
                            <label for="userName">(price)  سعر العرض  *</label>
                            <input type="number" name="price"  min=1 maxlength="6" oninput="validity.valid||(value='');" class="form-control " required>

                        </div>
                    </div>



                    <div class="col-xs-6">
                        <div class="form-group">
                            <label>  تاريخ بداية العرض</label>
                            <input type="text" name="start_at" class="form-control datepicker  " required />

                        </div>
                    </div>



                    <div class="col-xs-6">
                        <div class="form-group">
                            <label>  تاريخ انتهاء العرض</label>
                            <input type="text" name="end_at" class="form-control datepicker  " required/>

                        </div>
                    </div>



                    <br>

                    <div class="form-group text-right m-t-20">
                        <button id="hiddenButton" class="btn btn-primary waves-effect waves-light m-t-20" type="submit">
                            حفظ البيانات
                        </button>
                        <button onclick="window.history.back();return false;" type="reset"
                                class="btn btn-default waves-effect waves-light m-l-5 m-t-20">
                            إلغاء
                        </button>
                    </div>

                </div>
            </div><!-- end col -->

            <div class="col-lg-4" id="renderHtml">
                <div class="card-box" style="overflow: hidden;">
                    <h4 class="header-title   text-center">  إختيار منتج </h4>


                </div>
            </div><!-- end col -->
        </div>
        <!-- end row -->
    </form>
@endsection

@section('scripts')

    <script>

        function validImages() {

            var images = $( "input[name='image']" ).val();


            if ( images === undefined || images === ""   ) {
                var shortCutFunction = 'error';
                var msg = 'من فضلك إختار   صورة واحدة علي الأقل  ';
                var title = 'نجاح';
                toastr.options = {
                    positionClass: 'toast-top-left',
                    preventDuplicates: true,
                    onclick: null
                };
                $toastlast = toastr[shortCutFunction](msg, title);
                return false;
            }

            return true;
        }

        $('form').on('submit', function (e) {

            e.preventDefault();

            var formData = new FormData(this);

            var form = $(this);
            form.parsley().validate();

            // if (form.parsley().isValid() && validImages()){
                if (form.parsley().isValid()  ){
                $('.loading').show();

                $.ajax({
                    type: 'POST',
                    url: $(this).attr('action'),
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        $('.loading').hide();
                        messageDisplay( 'نجاح' ,data.message )
                        // setTimeout(function () {
                        //     window.location.href = data.url;
                        // }, 2000);
                    },
                    error: function (data) {
                        $('.loading').hide();
                        errorMessageTostar('فشل',data.responseJSON.error[0]);
                    }
                });
            }else {

            }
        });

        function messageDisplay($title, $message) {
            var shortCutFunction = 'success';
            var msg = $message;
            var title = $title;
            toastr.options = {
                positionClass: 'toast-top-left',
                onclick: null
            };
            $toastlast = toastr[shortCutFunction](msg, title);
        }

        function errorMessageTostar($title, $message) {
            var shortCutFunction = 'error';
            var msg = $message;
            var title = $title;
            toastr.options = {
                positionClass: 'toast-top-left',
                onclick: null
            };
            var $toast = toastr[shortCutFunction](msg, title);
            $toastlast = $toast;
        }


        $('.product_change').on('change', function (e) {
            var product_id  =   $(this).val();

                $('.loading').show();

                $.ajax({
                    type: 'POST',
                    url: "{{ route('agent_products.renderProductData') }}",
                    data: {product_id : product_id},
                    datatype:'json',
                    success: function (data) {
                        $('.loading').hide();
                        $("#renderHtml").html(data.html)

                    },
                    error: function (data) {
                        $('.loading').hide();
                        errorMessageTostar('نعتذر', 'للاسف يوجد خطا ما ')
                    }
                });

        });

    </script>


@endsection

resources/views/admin/agent_product_offers/index.blade.php
@extends('admin.layouts.master')

@section('title', __('maincp.cities'))

@section('content')


    <!-- Page-Title -->
    <div class="row">
        <div class="col-sm-12">
                        <div class="btn-group pull-right m-t-15 ">
                            <a href="{{ route('agent_product_offer.create') }} "
                               type="button" class="btn btn-custom waves-effect waves-light"
                               aria-expanded="false">
                            <span class="m-l-5">
                            <i class="fa fa-plus"></i>
                            </span>
                                إضافة عرض
                            </a>
                        </div>
            <h4 class="page-title">{{$pageName}} </h4>
        </div>
    </div>



    <div class="row">
        <div class="col-sm-12">
            <div class="card-box table-responsive">

                <div class="dropdown pull-right">
                    {{--<a href="#" class="dropdown-toggle card-drop" data-toggle="dropdown" aria-expanded="false">--}}
                    {{--<i class="zmdi zmdi-more-vert"></i> --}}
                    {{--</a>--}}

                </div>

                <h4 class="header-title m-t-0 m-b-30"> إدارة {{$pageName}}</h4>

                <table id="datatable-fixed-header" class="table table-striped table-bordered dt-responsive nowrap"
                       cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>اسم المنتج </th>
                        <th>سعر المنتج </th>
                        <th>سعر خصم المنتج </th>
                        <th>نسبة خصم المنتج </th>
                        <th>تاريخ بداية العرض </th>
                        <th>تاريخ نهاية العرض </th>
                        <th>@lang('trans.status')</th>
                        <th>@lang('trans.options')</th>
                    </tr>
                    </thead>
                    <tbody>

                    @foreach($offers as $row)
                        <tr>
                            <td>{{ $row->name_ar }}</td>
                            <td>{{ $row->product_price }}</td>
                            <td>{{ $row->offer_price }}</td>
                            <td>{{ $row->percentage . " % " }}</td>
                            <td>   {{ $row->start_at->format("Y/m/d") }}  </td>
                            <td>   {{ $row->end_at->format("Y/m/d") }}  </td>

                            <td>

                                <div class="StatusActive{{ $row->id }}"  style="display: {{ $row->is_suspend == 0 ? "none" : "block" }}; text-align: center;">
                                    <img  width="23px" src="{{ asset('assets/admin/images/false.png') }}" alt="">
                                </div>

                                <div class="StatusNotActive{{ $row->id }}" style="display: {{ $row->is_suspend == 0 ? "block" : "none" }};  text-align: center;">
                                    <img width="23px" src="{{ asset('assets/admin/images/ok.png') }}" alt="">
                                </div>

                            </td>

                            <td>

                                <a href="{{ route('agent_product_offer.edit', $row->id) }}"
                                   data-toggle="tooltip" data-placement="top"
                                   data-original-title=" تعديل"
                                   class="btn btn-icon btn-xs waves-effect  btn-info">
                                    <i class="fa fa-edit"></i>
                                </a>

                                <a href="javascript:;" data-id="{{ $row->id }}" data-type="0"
                                   data-url="{{ route('agent_product_offer.suspend') }}"
                                   style="@if($row->is_suspend == 0) display: none;  @endif"
                                   class="btn btn-xs  btn-success success suspendElement suspend{{ $row->id }}"
                                   id="suspendElement" data-message="@lang('trans.activationElement')"
                                   data-toggle="tooltip" data-placement="top"
                                   title="" data-original-title="تفعيل">
                                    <i class="fa fa-unlock"></i>
                                </a>

                                <a href="javascript:;" data-id="{{ $row->id }}" data-type="1"
                                   data-url="{{ route('agent_product_offer.suspend') }}"
                                   style="@if($row->is_suspend == 1) display: none;  @endif"
                                   class="btn btn-xs btn-trans btn-danger danger suspendElement unsuspend{{ $row->id }}"
                                   id="suspendElement"
                                   data-message="@lang('trans.stopActivationElememt')"
                                   data-toggle="tooltip" data-placement="top"
                                   title="" data-original-title="{{ __('trans.suspend') }}">
                                    <i class="fa fa-lock"></i>
                                </a>

                            </td>
                        </tr>
                    @endforeach

                    </tbody>
                </table>
            </div>
        </div><!-- end col -->
    </div>
    <!-- end row -->


@endsection


@section('scripts')



    <script>

        $('body').on('click', '.removeElement', function () {
            var id = $(this).attr('data-id');
            var url = $(this).attr('data-url');
            var $tr = $(this).closest($('#elementRow' + id).parent().parent());
            swal({
                title: "هل انت متأكد؟",
                text: "يمكنك استرجاع المحذوفات مرة اخرى لا تقلق.",
                type: "error",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "موافق",
                cancelButtonText: "إلغاء",
                confirmButtonClass: 'btn-danger waves-effect waves-light',
                closeOnConfirm: true,
                closeOnCancel: true,
            }, function (isConfirm) {
                if (isConfirm) {
                    $.ajax({
                        type: 'POST',
                        url: url,
                        data: {id: id},
                        dataType: 'json',
                        success: function (data) {

                            if (data.status == true) {
                                var shortCutFunction = 'success';
                                var msg = 'لقد تمت عملية الحذف بنجاح.';
                                var title = data.title;
                                toastr.options = {
                                    positionClass: 'toast-top-left',
                                    onclick: null
                                };
                                var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
                                $toastlast = $toast;

                                $tr.find('td').fadeOut(1000, function () {
                                    $tr.remove();
                                });
                            }

                            if (data.status == false) {
                                var shortCutFunction = 'warning';
                                var msg =data.message;
                                var title = data.title;
                                toastr.options = {
                                    positionClass: 'toast-top-left',
                                    onclick: null
                                };
                                var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
                                $toastlast = $toast;

                            }
                        }
                    });
                }
            });
        });





        $(document).ready(function () {
            //$('#datatable').dataTable();
            //$('#datatable-keytable').DataTable( { keys: true } );
            $('#datatable-responsive').DataTable();

        });


    </script>


@endsection