routes/web.php
Route::group(['prefix' => 'administrator','namespace' => 'Admin', 'middleware' => ['admin']], function () {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('admin.home');

    Route::resource('helpAdmin', 'HelpAdminController');
    Route::get('helpAdmin/{id}/delete', 'HelpAdminController@delete')->name('helpAdmin.delete');
    Route::post('helpAdmin/{id}/delete', 'HelpAdminController@deleteHelpAdmin')->name('helpAdmin.message.delete');
    Route::post('helpAdmin/{id}/suspend', 'HelpAdminController@suspendHelpAdmin')->name('helpAdmin.message.suspend');
    Route::get('user/{id}/delete', 'UsersController@delete')->name('user.for.delete');
    Route::post('user/suspend', 'HelpAdminController@suspend')->name('user.suspend');
    // Roles routes ..........
    Route::resource('roles', 'RolesController');
    Route::post('role/delete', 'RolesController@delete')->name('role.delete');

    Route::resource('users', 'UsersController');
    Route::post('refuseUser','UsersController@refuseUser')->name('user.refuseUser');
    Route::post('reAcceptUser','UsersController@reAcceptUser')->name('user.reAcceptUser');
    Route::post('accepted','UsersController@accpetedUser')->name('user.accepted');
    Route::post('suspendUser','UsersController@suspendUser')->name('user.suspendUser');

    Route::resource('deliveries', 'DeliveryController');
    Route::post('deliveries/accepted','DeliveryController@accpetedUser')->name('deliveries.accepted');
    Route::post('deliveries/refuseUser','DeliveryController@refuseUser')->name('deliveries.refuseUser');

    Route::resource('agents', 'AgentController');

    Route::resource('cities', 'CitiesController');
    Route::post('cities/delete', 'CitiesController@delete')->name('cities.delete');
    Route::post('city/suspend', 'CitiesController@suspend')->name('city.suspend');

    // -------------------------------------- products .................
    Route::resource('products', 'ProductController');
    Route::post('products/delete', 'ProductController@delete')->name('products.delete');
    Route::post('products/suspend', 'ProductController@suspend')->name('products.suspend');

    // -------------------------------------- agent products .................
    Route::resource('agent_products', 'AgentProductController');
    Route::post('agent_products/delete', 'AgentProductController@delete')->name('agent_products.delete');
    Route::post('agent_products/suspend', 'AgentProductController@suspend')->name('agent_products.suspend');
    Route::post('agent_products/renderProductData', 'AgentProductController@renderProductData')->name('agent_products.renderProductData');

    // -------------------------------------- agent products Offers .................
    Route::resource('agent_product_offer', 'AgentProductOfferController');
    Route::post('agent_product_offer/delete', 'AgentProductOfferController@delete')->name('agent_product_offer.delete');
    Route::post('agent_product_offer/suspend', 'AgentProductOfferController@suspend')->name('agent_product_offer.suspend');

    // -------------------------------------- offer products .................
    Route::resource('offer_products', 'OfferProductController');
    Route::post('offer_products/delete', 'OfferProductController@delete')->name('offer_products.delete');
    Route::post('offer_products/suspend', 'OfferProductController@suspend')->name('offer_products.suspend');

    // --------------------------------------  promo_codes .................
    Route::resource('promo_codes', 'PromoCodesController');
    Route::post('promo_codes/delete', 'PromoCodesController@delete')->name('promo_codes.delete');
    Route::post('promo_codes/suspend', 'PromoCodesController@suspend')->name('promo_codes.suspend');

    // -------------------------------------- categories .................
    Route::resource('categories', 'CategoriesController');
    Route::post('categories/delete', 'CategoriesController@delete')->name('categories.delete');
    Route::post('categories/suspend', 'CategoriesController@suspend')->name('categories.suspend');

    // -------------------------------------- cars .................
    Route::resource('cars', 'CarController');
    Route::post('cars/delete', 'CarController@delete')->name('cars.delete');
    Route::post('cars/suspend', 'CarController@suspend')->name('cars.suspend');

    // -------------------------------------- brands .................
    Route::resource('brands', 'BrandController');
    Route::post('brands/delete', 'BrandController@delete')->name('brands.delete');
    Route::post('brands/suspend', 'BrandController@suspend')->name('brands.suspend');

    // -------------------------------------- charity_addresses .................
    Route::resource('charity_addresses', 'CharityAddressController');
    Route::post('charity_addresses/delete', 'CharityAddressController@delete')->name('charity_addresses.delete');
    Route::post('charity_addresses/suspend', 'CharityAddressController@suspend')->name('charity_addresses.suspend');

    // -------------------------------------- notifications_admin .................
    Route::resource('notifications_admin', 'NotificationController');
    Route::get('notifications/promo_code', 'NotificationController@promo_code')->name('notifications_admin.promo_code');
    Route::get('notifications/get_promo_code', 'NotificationController@get_promo_code')->name('notifications_admin.get_promo_code');
    Route::get('notifications/renderUsesData', 'NotificationController@renderUsesData')->name('notifications_admin.renderUsesData');
    Route::post('notifications_admin/send_promo_code', 'NotificationController@send_promo_code')->name('notifications_admin.send_promo_code');
    Route::post('notifications_admin/delete', 'NotificationController@delete')->name('notifications_admin.delete');

    Route::get('settings/contacts', 'SettingsController@contactus')->name('settings.contactus');
    Route::get('settings/orderPricing', 'SettingsController@orderPricing')->name('settings.order.pricing');
    Route::get('settings/aboutus', 'SettingsController@aboutus')->name('settings.aboutus');
    Route::get('settings/terms', 'SettingsController@terms')->name('settings.terms');
    Route::get('settings/termsProvider', 'SettingsController@termsGym')->name('settings.termsGym');
    Route::get('settings/termsDelivery', 'SettingsController@termsDelivery')->name('settings.termsDelivery');

    Route::post('/settings', 'SettingsController@store')->name('administrator.settings.store');
    Route::post('/settings/packageStore', 'SettingsController@packageStore')->name('administrator.package.store');


    Route::resource('banks', 'BanksController');
    Route::post('bank/suspend', 'BanksController@suspend')->name('bank.suspend');

    Route::get('bank-transfer-admin', 'BankTransferController@index')->name('bank-transfer-admin');
    Route::post('accept-transfer-admin', 'BankTransferController@accepted')->name('accept-transfer-admin');
    Route::post('refuse-transfer-admin', 'BankTransferController@refuse')->name('refuse-transfer-admin');

    Route::get('subscriptions-dealers', 'SubscriptionController@index')->name('subscriptions-dealers');
    Route::post('subscriptions-dealers', 'SubscriptionController@accepted')->name('accept-subscriptions-dealers');


    Route::resource('contact_us_inbox', 'ContactUsController');
    Route::get('updateIsRead', 'ContactUsController@updateIsRead')->name('admin.support.updateIsRead');
    Route::get('updateIsDeleted', 'ContactUsController@updateIsDeleted')->name('admin.support.updateIsDeleted');
    Route::get('removeAllMessages', 'ContactUsController@removeAllMessages')->name('admin.support.removeAllMessages');


    Route::get('invoices_orders','ReportsController@invoices_orders')->name("admin.invoices_orders");
    Route::get('invoices_orders_show/{user}','ReportsController@invoices_orders_show')->name("admin.invoices_orders_show");
    Route::get('invoices_orders_excel/{user}','ReportsController@invoices_orders_excel')->name("admin.invoices_orders_excel");
    Route::post('/logout', 'LoginController@logout')->name('administrator.logout');

});



Route::get('/sub', function (Illuminate\Http\Request $request) {

    $cities =\App\Models\City::whereParentId($request->id)->get();

    if (!empty($cities) && count($cities) > 0){
        return response()->json( $cities);
    }else{

        return response()->json(401);
    }


})->name('getSub');



Route::get('roles', function () {

    $user = auth()->user();
//    $user->retract('admin');
    $user->assign('*');
    Bouncer::allow('*')->everything();
    $user->allow('users_manage');
});


Route::post('user/update/token', function (Illuminate\Http\Request $request) {

    $user = \App\User::whereId($request->id)->first();


    if ($request->token) {
        $data = \App\Models\Device::where('device', $request->token)->first();
        if ($data) {
            $data->user_id = $user->id;
            $data->save();
        } else {


            $data = new \App\Models\Device;
            $data->device = $request->token;
            $data->user_id = $user->id;
            $data->device_type = 'web';
            $data->save();
        }
    }


})->name('user.update.token');


Route::get('test_image',function (){

    $user = \App\User::with('profile.media')->find(5);

    $image = $user->profile->getMedia('default', ['image' => 'profile']);

//    $image = $user->profile->getMedia('default');
//    $image = $user->profile->getFirstMediaUrl();
    $data = [
        'url' => $image->first() ? $image[0]->getUrl() : null,
        'name' => 'ramy'
    ];
    return $data;
});


Route::get("php_info",function (){

//    phpinfo();
});


Route::get("test_tabel",function (){

    $users =  DB::select('describe users');
//    $data = (DB::select(DB::raw('SHOW FIELDS FROM users')));

//    return collect($users)->reject(function ($value, $key) {

app/Models/PromoCode.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PromoCode extends Model
{
    protected $guarded = [];

    protected $dates = ['start_at' , 'end_at'];
}

app/Http/Controllers/Admin/PromoCodesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\PromoCodeVaild;
use App\Models\PromoCode;
use Illuminate\Http\Request;

class PromoCodesController extends Controller
{
    public function index(){
        $codes = PromoCode::where('is_deleted',0)->get();

        $pageName = 'إدارة أكواد الخصم';

        return view('admin.promo_codes.index',compact('codes', 'pageName'));
    }

    public function create(){
        $pageName = 'إضافة كواد الخصم';
        return view('admin.promo_codes.create',compact('pageName'));
    }

    public function store(PromoCodeVaild  $request){

        PromoCode::create($request->validated());
        return response()->json([
            'status' => true,
            "message" => __('trans.addingSuccess',['itemName' => 'الكود']),
            "url" => route('promo_codes.index'),
        ]);
    }


    public function edit($id){

        $promo_code = PromoCode::findOrFail($id);

        $pageName = 'تعديل  كود الخصم';

        return view('admin.promo_codes.edit',compact('pageName','promo_code'));
    }

    public function update(PromoCodeVaild  $request , $id){
        $promo_code = PromoCode::findOrFail($id);

        $promo_code->update($request->validated());

        return response()->json([
            'status' => true,
            "message" => __('trans.editSuccess',['itemName' => 'الكود']),
            "url" => route('promo_codes.index'),
        ]);
    }



    public function delete(Request  $request){

        $promo_code = PromoCode::findOrFail($request->id);

        $promo_code->update(['is_deleted' => 1]);

        return response()->json([
            'status' => true,
            'data' => $promo_code->id
        ]);
    }

    public function suspend(Request $request)
    {
        $model = PromoCode::findOrFail($request->id);
        $model->is_suspend = $request->type;
        if ($request->type == 1) {

            $message = "لقد تم حظر كود الخصم بنجاح";
        } else {
            $message = "لقد تم فك الحظر على  كود الخصم بنجاح";
        }

        if ($model->save()) {
            return response()->json([
                'status' => true,
                'message' => $message,
                'id' => $request->id,
                'type' => $request->type

            ]);
        }

    }

}

resources/views/admin/promo_codes/create.blade.php
@extends('admin.layouts.master')
@section('title', __('maincp.users_manager'))


@section('styles')



@endsection

@section('content')



    <form   method="POST" action="{{ route('promo_codes.store') }}" enctype="multipart/form-data"
            data-parsley-validate novalidate>
    {{ csrf_field() }}

    <!-- Page-Title -->
        <div class="row">
            <div class="col-lg-12  ">
                <div class="btn-group pull-right m-t-15">
                    <button type="button" class="btn btn-custom  waves-effect waves-light"
                            onclick="window.history.back();return false;"> رجوع <span class="m-l-5"><i
                                class="fa fa-reply"></i></span>
                    </button>
                </div>
                <h4 class="page-title">إدارة {{$pageName}}</h4>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12  ">
                <div class="card-box">


                    <h4 class="header-title m-t-0 m-b-30"> إضافة {{$pageName}}</h4>

                    <div class="row">


                        <div class="col-xs-6">
                            <div class="form-group">
                                <label for="times"> الكود للمستخدم </label>
                                <input type="number" name="code" min=1 maxlength="10" oninput="validity.valid||(value='');"
                                       class="form-control    number " required />
                                <p class="help-block" id="error_times"></p>
                            </div>
                        </div>



                        <div class="col-xs-6">
                            <div class="form-group">
                                <label for="date">تاريخ بداية إستخدام الكود </label>
                                <div class="input-group">
                                    <input type="text" name="start_at"  class="form-control   datepicker  " required />
                                    <span class="input-group-addon bg-primary b-0 text-white"><i class="ti-calendar"></i></span>
                                    <p class="help-block" id="error_date"></p>
                                </div>
                            </div>
                        </div>


                        <div class="col-xs-6">
                            <div class="form-group">
                                <label for="end_at">تاريخ نهاية إستخدام الكود </label>
                                <div class="input-group">
                                    <input type="text" name="end_at"    class="form-control  datepicker  " required />
                                    <span class="input-group-addon bg-primary b-0 text-white"><i class="ti-calendar"></i></span>
                                    <p class="help-block" id="error_end_at"></p>
                                </div>
                            </div>
                        </div>

                        <div class="col-xs-6">
                            <div class="form-group">
                                <label for="times">عدد مرات  إستخدام الكود للمستخدم </label>
                                <input type="number" name="times" min=1 maxlength="6" oninput="validity.valid||(value='');"
                                       class="form-control    number " required />
                                <p class="help-block" id="error_times"></p>
                            </div>
                        </div>

                        <div class="col-xs-6">
                            <div class="form-group">
                                <label>نسبة خصم إستخدام الكود للمستخدم   </label>

                                <div class="input-group bootstrap-touchspin">
                                    <input class="form-control  " type="text" required
                                           name="percent"  placeholder="نسبة خصم إستخدام الكود للمستخدم"  >

                                    <span class="input-group-addon bootstrap-touchspin-postfix">%</span>
                                </div>
                            </div>
                        </div>


                    </div>


                    <div class="form-group text-right m-t-20">
                        <button   class="btn btn-warning waves-effect waves-light m-t-20" type="submit">
                            @lang('maincp.save_data')
                        </button>
                        <button onclick="window.history.back();return false;" type="reset"
                                class="btn btn-default waves-effect waves-light m-l-5 m-t-20">
                            @lang('maincp.disable')
                        </button>
                    </div>

                </div>
            </div><!-- end col -->


        </div>
        <!-- end row -->
    </form>

@endsection



@section('scripts')


    <script type="text/javascript"
            src="{{ request()->root() }}/assets/admin/js/validate-{{ config('app.locale') }}.js"></script>
    <script type="text/javascript">
        // $(document).ready(function() {
        //     $(function() {
        //         $("#select_date").on('change', function(){
        //             var date = Date.parse($(this).val());
        //             if (date < Date.now()){
        //                 var shortCutFunction = 'error';
        //                 var msg = 'من فضلك إختار تاريخ قدام ';
        //                 var title = 'نجاح';
        //                 toastr.options = {
        //                     positionClass: 'toast-top-left',
        //                     onclick: null
        //                 };
        //                 var $toast = toastr[shortCutFunction](msg, title);
        //                 $toastlast = $toast;
        //                 $(this).val('');
        //             }
        //         });
        //     });
        // });



        $('form').on('submit', function (e) {

            e.preventDefault();

            var formData = new FormData(this);

            var form = $(this);
            form.parsley().validate();

            if (form.parsley().isValid()){
                $('.loading').show();

                $.ajax({
                    type: 'POST',
                    url: $(this).attr('action'),
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        $('.loading').hide();
                        messageDisplay( 'نجاح' ,data.message )
                        setTimeout(function () {
                            window.location.href = data.url;
                        }, 2000);
                    },
                    error: function (data) {
                        $('.loading').hide();
                        errorMessageTostar('فشل',data.responseJSON.error[0]);
                    }
                });
            }else {
                $('.loading').hide();
            }
        });



        function messageDisplay($title, $message) {
            var shortCutFunction = 'success';
            var msg = $message;
            var title = $title;
            toastr.options = {
                positionClass: 'toast-top-left',
                onclick: null
            };
            $toastlast = toastr[shortCutFunction](msg, title);
        }

        function errorMessageTostar($title, $message) {
            var shortCutFunction = 'error';
            var msg = $message;
            var title = $title;
            toastr.options = {
                positionClass: 'toast-top-left',
                onclick: null
            };
            var $toast = toastr[shortCutFunction](msg, title);
            $toastlast = $toast;
        }


    </script>
@endsection

resources/views/admin/promo_codes/edit.blade.php
@extends('admin.layouts.master')
@section('title', __('maincp.users_manager'))


@section('styles')



@endsection

@section('content')



    <form   method="POST" action="{{ route('promo_codes.update', $promo_code->id) }}" enctype="multipart/form-data"
            data-parsley-validate novalidate>
    {{ csrf_field() }}
    {{ method_field('PUT') }}

    <!-- Page-Title -->
        <div class="row">
            <div class="col-lg-12  ">
                <div class="btn-group pull-right m-t-15">
                    <button type="button" class="btn btn-custom  waves-effect waves-light"
                            onclick="window.history.back();return false;"> رجوع <span class="m-l-5"><i
                                class="fa fa-reply"></i></span>
                    </button>
                </div>
                <h4 class="page-title">إدارة {{$pageName}}</h4>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12  ">
                <div class="card-box">


                    <h4 class="header-title m-t-0 m-b-30"> تعديل {{$pageName}}</h4>

                    <div class="row">

                        <div class="col-xs-6">
                            <div class="form-group">
                                <label for="times"> الكود للمستخدم </label>
                                <input type="number" name="code" min=1 maxlength="10" oninput="validity.valid||(value='');"
                                       class="form-control number " value="{{$promo_code->code}}" required />
                                <p class="help-block" id="error_times"></p>
                            </div>
                        </div>

                        <div class="col-xs-6">
                            <div class="form-group">
                                <label for="date">تاريخ بداية إستخدام الكود </label>
                                <div class="input-group">
                                    <input type="text" name="start_at"  class="form-control  datepicker  "
                                           value="{{$promo_code->start_at->format("Y-m-d")}}" required />
                                    <span class="input-group-addon bg-primary b-0 text-white"><i class="ti-calendar"></i></span>
                                    <p class="help-block" id="error_date"></p>
                                </div>
                            </div>
                        </div>


                        <div class="col-xs-6">
                            <div class="form-group">
                                <label for="end_at">تاريخ نهاية إستخدام الكود </label>
                                <div class="input-group">
                                    <input type="text" name="end_at"  value="{{$promo_code->end_at->format("Y-m-d")}}"   class="form-control  datepicker  " required />
                                    <span class="input-group-addon bg-primary b-0 text-white"><i class="ti-calendar"></i></span>
                                    <p class="help-block" id="error_end_at"></p>
                                </div>
                            </div>
                        </div>

                        <div class="col-xs-6">
                            <div class="form-group">
                                <label for="times">عدد مرات  إستخدام الكود للمستخدم </label>
                                <input type="number" name="times" value="{{$promo_code->times}}" min=1 maxlength="6" oninput="validity.valid||(value='');"
                                       class="form-control    number " required />
                                <p class="help-block" id="error_times"></p>
                            </div>
                        </div>

                        <div class="col-xs-6">
                            <div class="form-group">
                                <label>نسبة خصم إستخدام الكود للمستخدم   </label>

                                <div class="input-group bootstrap-touchspin">
                                    <input class="form-control  " min="1" value="{{$promo_code->percent}}" type="text" required
                                           name="percent"  placeholder="نسبة خصم إستخدام الكود للمستخدم"  >

                                    <span class="input-group-addon bootstrap-touchspin-postfix">%</span>
                                </div>
                            </div>
                        </div>


                    </div>


                    <div class="form-group text-right m-t-20">
                        <button   class="btn btn-warning waves-effect waves-light m-t-20" type="submit">
                            @lang('maincp.save_data')
                        </button>
                        <button onclick="window.history.back();return false;" type="reset"
                                class="btn btn-default waves-effect waves-light m-l-5 m-t-20">
                            @lang('maincp.disable')
                        </button>
                    </div>

                </div>
            </div><!-- end col -->


        </div>
        <!-- end row -->
    </form>

@endsection



@section('scripts')


    <script type="text/javascript"
            src="{{ request()->root() }}/assets/admin/js/validate-{{ config('app.locale') }}.js"></script>
    <script type="text/javascript">
        // $(document).ready(function() {
        //     $(function() {
        //         $("#select_date").on('change', function(){
        //             var date = Date.parse($(this).val());
        //             if (date < Date.now()){
        //                 var shortCutFunction = 'error';
        //                 var msg = 'من فضلك إختار تاريخ قدام ';
        //                 var title = 'نجاح';
        //                 toastr.options = {
        //                     positionClass: 'toast-top-left',
        //                     onclick: null
        //                 };
        //                 var $toast = toastr[shortCutFunction](msg, title);
        //                 $toastlast = $toast;
        //                 $(this).val('');
        //             }
        //         });
        //     });
        // });



        $('form').on('submit', function (e) {

            e.preventDefault();

            var formData = new FormData(this);

            var form = $(this);
            form.parsley().validate();

            if (form.parsley().isValid()){
                $('.loading').show();

                $.ajax({
                    type: 'POST',
                    url: $(this).attr('action'),
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        $('.loading').hide();
                        messageDisplay( 'نجاح' ,data.message )
                        setTimeout(function () {
                            window.location.href = data.url;
                        }, 2000);
                    },
                    error: function (data) {
                        $('.loading').hide();
                        errorMessageTostar('فشل',data.responseJSON.error[0]);
                    }
                });
            }else {
                $('.loading').hide();
            }
        });



        function messageDisplay($title, $message) {
            var shortCutFunction = 'success';
            var msg = $message;
            var title = $title;
            toastr.options = {
                positionClass: 'toast-top-left',
                onclick: null
            };
            $toastlast = toastr[shortCutFunction](msg, title);
        }

        function errorMessageTostar($title, $message) {
            var shortCutFunction = 'error';
            var msg = $message;
            var title = $title;
            toastr.options = {
                positionClass: 'toast-top-left',
                onclick: null
            };
            var $toast = toastr[shortCutFunction](msg, title);
            $toastlast = $toast;
        }


    </script>
@endsection