routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
//
//Auth::routes();
//
//Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

//Route::get('lang/{language}', 'LanguageController@switchLang')->name('lang.switch');

Route::group(['prefix' => 'administrator'], function () {


    Route::get('/login', 'Admin\LoginController@login')->name('admin.login');
    Route::post('/login', 'Admin\LoginController@postLogin')->name('admin.postLogin');

    // Password Reset Routes...

    Route::get('password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('administrator.password.request');
    Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('administrator.password.email');
    Route::get('password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('administrator.password.reset.token');
    Route::post('password/reset', 'Admin\Auth\ResetPasswordController@reset');

});
Route::group(['prefix' => 'administrator','namespace' => 'Admin', 'middleware' => ['admin']], function () {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('admin.home');

    Route::resource('helpAdmin', 'HelpAdminController');
    Route::get('helpAdmin/{id}/delete', 'HelpAdminController@delete')->name('helpAdmin.delete');
    Route::post('helpAdmin/{id}/delete', 'HelpAdminController@deleteHelpAdmin')->name('helpAdmin.message.delete');
    Route::post('helpAdmin/{id}/suspend', 'HelpAdminController@suspendHelpAdmin')->name('helpAdmin.message.suspend');
    Route::get('user/{id}/delete', 'UsersController@delete')->name('user.for.delete');
    Route::post('user/suspend', 'HelpAdminController@suspend')->name('user.suspend');
    // Roles routes ..........
    Route::resource('roles', 'RolesController');
    Route::post('role/delete', 'RolesController@delete')->name('role.delete');

    Route::resource('users', 'UsersController');
    Route::post('refuseUser','UsersController@refuseUser')->name('user.refuseUser');
    Route::post('reAcceptUser','UsersController@reAcceptUser')->name('user.reAcceptUser');
    Route::post('accepted','UsersController@accpetedUser')->name('user.accepted');
    Route::post('suspendUser','UsersController@suspendUser')->name('user.suspendUser');

    Route::resource('deliveries', 'DeliveryController');
    Route::post('deliveries/accepted','DeliveryController@accpetedUser')->name('deliveries.accepted');
    Route::post('deliveries/refuseUser','DeliveryController@refuseUser')->name('deliveries.refuseUser');

    Route::resource('agents', 'AgentController');

    Route::resource('cities', 'CitiesController');
    Route::post('cities/delete', 'CitiesController@delete')->name('cities.delete');
    Route::post('city/suspend', 'CitiesController@suspend')->name('city.suspend');

    // -------------------------------------- products .................
    Route::resource('products', 'ProductController');
    Route::post('products/delete', 'ProductController@delete')->name('products.delete');
    Route::post('products/suspend', 'ProductController@suspend')->name('products.suspend');

    // -------------------------------------- agent products .................
    Route::resource('agent_products', 'AgentProductController');
    Route::post('agent_products/delete', 'AgentProductController@delete')->name('agent_products.delete');
    Route::post('agent_products/suspend', 'AgentProductController@suspend')->name('agent_products.suspend');
    Route::post('agent_products/renderProductData', 'AgentProductController@renderProductData')->name('agent_products.renderProductData');

    // -------------------------------------- agent products Offers .................
    Route::resource('agent_product_offer', 'AgentProductOfferController');
    Route::post('agent_product_offer/delete', 'AgentProductOfferController@delete')->name('agent_product_offer.delete');
    Route::post('agent_product_offer/suspend', 'AgentProductOfferController@suspend')->name('agent_product_offer.suspend');

    // -------------------------------------- offer products .................
    Route::resource('offer_products', 'OfferProductController');
    Route::post('offer_products/delete', 'OfferProductController@delete')->name('offer_products.delete');
    Route::post('offer_products/suspend', 'OfferProductController@suspend')->name('offer_products.suspend');

    // --------------------------------------  promo_codes .................
    Route::resource('promo_codes', 'PromoCodesController');
    Route::post('promo_codes/delete', 'PromoCodesController@delete')->name('promo_codes.delete');
    Route::post('promo_codes/suspend', 'PromoCodesController@suspend')->name('promo_codes.suspend');

    // -------------------------------------- categories .................
    Route::resource('categories', 'CategoriesController');
    Route::post('categories/delete', 'CategoriesController@delete')->name('categories.delete');
    Route::post('categories/suspend', 'CategoriesController@suspend')->name('categories.suspend');

    // -------------------------------------- cars .................
    Route::resource('cars', 'CarController');
    Route::post('cars/delete', 'CarController@delete')->name('cars.delete');
    Route::post('cars/suspend', 'CarController@suspend')->name('cars.suspend');

    // -------------------------------------- brands .................
    Route::resource('brands', 'BrandController');
    Route::post('brands/delete', 'BrandController@delete')->name('brands.delete');
    Route::post('brands/suspend', 'BrandController@suspend')->name('brands.suspend');

    // -------------------------------------- charity_addresses .................
    Route::resource('charity_addresses', 'CharityAddressController');
    Route::post('charity_addresses/delete', 'CharityAddressController@delete')->name('charity_addresses.delete');
    Route::post('charity_addresses/suspend', 'CharityAddressController@suspend')->name('charity_addresses.suspend');

    // -------------------------------------- notifications_admin .................
    Route::resource('notifications_admin', 'NotificationController');
    Route::get('notifications/promo_code', 'NotificationController@promo_code')->name('notifications_admin.promo_code');
    Route::get('notifications/get_promo_code', 'NotificationController@get_promo_code')->name('notifications_admin.get_promo_code');
    Route::get('notifications/renderUsesData', 'NotificationController@renderUsesData')->name('notifications_admin.renderUsesData');
    Route::post('notifications_admin/send_promo_code', 'NotificationController@send_promo_code')->name('notifications_admin.send_promo_code');
    Route::post('notifications_admin/delete', 'NotificationController@delete')->name('notifications_admin.delete');

    Route::get('settings/contacts', 'SettingsController@contactus')->name('settings.contactus');
    Route::get('settings/orderPricing', 'SettingsController@orderPricing')->name('settings.order.pricing');
    Route::get('settings/aboutus', 'SettingsController@aboutus')->name('settings.aboutus');
    Route::get('settings/terms', 'SettingsController@terms')->name('settings.terms');
    Route::get('settings/termsProvider', 'SettingsController@termsGym')->name('settings.termsGym');
    Route::get('settings/termsDelivery', 'SettingsController@termsDelivery')->name('settings.termsDelivery');

    Route::post('/settings', 'SettingsController@store')->name('administrator.settings.store');
    Route::post('/settings/packageStore', 'SettingsController@packageStore')->name('administrator.package.store');


    Route::resource('banks', 'BanksController');
    Route::post('bank/suspend', 'BanksController@suspend')->name('bank.suspend');

    Route::get('bank-transfer-admin', 'BankTransferController@index')->name('bank-transfer-admin');
    Route::post('accept-transfer-admin', 'BankTransferController@accepted')->name('accept-transfer-admin');
    Route::post('refuse-transfer-admin', 'BankTransferController@refuse')->name('refuse-transfer-admin');

    Route::get('subscriptions-dealers', 'SubscriptionController@index')->name('subscriptions-dealers');
    Route::post('subscriptions-dealers', 'SubscriptionController@accepted')->name('accept-subscriptions-dealers');


    Route::resource('contact_us_inbox', 'ContactUsController');
    Route::get('updateIsRead', 'ContactUsController@updateIsRead')->name('admin.support.updateIsRead');
    Route::get('updateIsDeleted', 'ContactUsController@updateIsDeleted')->name('admin.support.updateIsDeleted');
    Route::get('removeAllMessages', 'ContactUsController@removeAllMessages')->name('admin.support.removeAllMessages');


    Route::get('invoices_orders','ReportsController@invoices_orders')->name("admin.invoices_orders");
    Route::get('invoices_orders_show/{user}','ReportsController@invoices_orders_show')->name("admin.invoices_orders_show");
    Route::get('invoices_orders_excel/{user}','ReportsController@invoices_orders_excel')->name("admin.invoices_orders_excel");
    Route::post('/logout', 'LoginController@logout')->name('administrator.logout');

});



Route::get('/sub', function (Illuminate\Http\Request $request) {

    $cities =\App\Models\City::whereParentId($request->id)->get();

    if (!empty($cities) && count($cities) > 0){
        return response()->json( $cities);
    }else{

        return response()->json(401);
    }


})->name('getSub');

app/Models/Category.php
<?php

namespace App\Models;

use App\Traits\GlobalScope;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Category extends Model implements HasMedia
{
    use  GlobalScope , InteractsWithMedia;

    public function products(){

        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\Admin\CategoryRequestVaild;
use App\Http\Requests\vaildImage;
use App\Models\Category;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;
use Validator;
use UploadImage;


class CategoriesController extends Controller
{

    public $public_path;

    public function __construct()
    {
        $this->public_path = 'files/categories/';
    }

    public function index(Request $request)
    {

	     $categories = Category::orderBy('order_by')->get();
	     $pageName = 'إدارة الاقسام ';

        return view('admin.categories.index',compact('categories','pageName'));
    }
    public function create()
    {

        $pageName = '   اسم القسم ';

        return view('admin.categories.create')->with(compact('pageName'));
    }

    public function store(CategoryRequestVaild $request)
    {
        $category = new Category;
        $category->name_ar = $request->name_ar;
        $category->name_en = $request->name_en;
        $category->order_by = $request->order_by;
        if ($request->hasFile('image')):
            $category->clearMediaCollection();
            $category->addMediaFromRequest('image')->toMediaCollection();
        endif;
        if ($category->save()) {
            $url =  route('categories.index');
            $name = ' القسم  ';
            return response()->json([
                'status' => true,
                "message" => __('trans.addingSuccess',['itemName' => $name]),
                "url" => $url,
            ]);
        }

    }


    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        $category = Category::findOrFail($id);

        $pageName = 'القسم';

        return view('admin.categories.edit')->with(compact('category',  'pageName' ));
    }


    public function update(CategoryRequestVaild $request, $id)
    {

        $category = Category::findOrFail($id);
        $category->name_ar = $request->name_ar;
        $category->name_en = $request->name_en;
        $category->order_by = $request->order_by;
        if ($request->hasFile('image')):
            $category->clearMediaCollection();
            $category->addMediaFromRequest('image')->toMediaCollection();
        endif;
        if ($category->save()) {

            $url =  route('categories.index');
            $name = 'القسم';

            return response()->json([
                'status' => true,
                "message" => __('trans.editSuccess',['itemName' => $name]),
                "url" => $url,

            ]);
        }

    }



       public function delete(Request $request){
	    if (!Gate::allows('settings_manage')) {
		 return abort(401);
	    }

	    $model = Category::findOrFail($request->id);

	    if (count($model->products) > 0) {

		 return response()->json([
		         'status' => false,
		         'message' => "عفواً, لا يمكنك حذف التخصص نظراً لوجود منتجات  فيها"
		 ]);
	    }


	    if ($model->delete()) {
             return response()->json([
                     'status' => true,
                     'data' => $model->id
             ]);
	    }

       }

       public function suspend(Request $request)
       {
            $model = Category::findOrFail($request->id);
            $model->is_suspend = $request->type;
            if ($request->type == 1) {

                $message = "لقد تم حظر القسم بنجاح";
            } else {
                $message = "لقد تم فك الحظر على القسم بنجاح";
            }

            if ($model->save()) {
             return response()->json([
                     'status' => true,
                     'message' => $message,
                     'id' => $request->id,
                     'type' => $request->type

             ]);
            }

       }



}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.master')
@section('title', __('maincp.users_manager'))


@section('styles')



@endsection
@section('content')



    <form method="POST" action="{{ route('categories.store') }}@if(request('type')  == 'subcategories' )?type=subcategories @endif" enctype="multipart/form-data"
          data-parsley-validate novalidate>
    {{ csrf_field() }}

    <!-- Page-Title -->
        <div class="row">
            <div class="col-lg-12  ">
                <div class="btn-group pull-right m-t-15">
                    <button type="button" class="btn btn-custom  waves-effect waves-light"
                            onclick="window.history.back();return false;"> رجوع <span class="m-l-5"><i
                                    class="fa fa-reply"></i></span>
                    </button>
                </div>
                <h4 class="page-title">إدارة {{$pageName}}</h4>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12  ">
                <div class="card-box">


                    <h4 class="header-title m-t-0 m-b-30"> إضافة {{$pageName}}</h4>

                    <div class="row">

                        @if(request('type'))
                            <div class="col-xs-6">
                                <div class="form-group">
                                    <label for="userName">إسم القسم الرئيسي*</label>
                                    <select name="parentId" id="" class="form-control requiredFieldWithMaxLenght" required>
                                        <option value="" selected disabled=""> إختر القسم</option>
                                        @foreach($cats as $value)
                                            <option value="{{ $value->id }}">{{ $value->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        @endif


                        <div class="col-xs-6">
                            <div class="form-group">
                                <label for="userName"> {{$pageName}}   باللغة العربية</label>
                                <input type="text" name="name_ar"
                                       class="form-control requiredFieldWithMaxLenght"
                                       required
                                       placeholder="   باللغة العربية{{$pageName}}  ..."/>
                                <p class="help-block" id="error_userName"></p>
                                @if($errors->has('name_ar'))
                                    <p class="help-block">
                                        {{ $errors->first('name_ar') }}
                                    </p>
                                @endif
                            </div>
                        </div>

                        <div class="col-xs-6">
                            <div class="form-group">
                                <label for="userName"> {{$pageName}}   باللغة الإنجليزية</label>
                                <input type="text" name="name_en"
                                       class="form-control requiredFieldWithMaxLenght"
                                       required
                                       placeholder="   باللغة الإنجليزية {{$pageName}}  ..."/>
                                <p class="help-block" id="error_userName"></p>
                                @if($errors->has('name_en'))
                                    <p class="help-block">
                                        {{ $errors->first('name_en') }}
                                    </p>
                                @endif
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <label for="order_by"> الرقم التسلسلي لترتيب الأقسام   </label>
                                <input type="number" name="order_by"
                                       class="form-control number" min=0 oninput="validity.valid||(value='');"
                                       required   placeholder="الرقم التسلسلي لترتيب الأقسام"/>
                            </div>
                        </div>

                        <div class="col-xs-6">
                            <div class="form-group">
                                <label for="usernames">صورة القسم  *</label>
                                <input type="file" name="image" class="dropify" data-max-file-size="6M"/>
                            </div>

                        </div>



                    </div>


                    <div class="form-group text-right m-t-20">
                        <button class="btn btn-warning waves-effect waves-light m-t-20" type="submit">
                            @lang('maincp.save_data')
                        </button>
                        <button onclick="window.history.back();return false;" type="reset"
                                class="btn btn-default waves-effect waves-light m-l-5 m-t-20">
                            @lang('maincp.disable')
                        </button>
                    </div>

                </div>
            </div><!-- end col -->


        </div>
        <!-- end row -->
    </form>

@endsection



@section('scripts')
    <script type="text/javascript"
            src="{{ request()->root() }}/assets/admin/js/validate-{{ config('app.locale') }}.js"></script>
    <script type="text/javascript">

        function validImages() {

            var images = $( "input[name='image']" ).val();


            if ( images === undefined || images === ""   ) {

                errorVaildationMessage('من فضلك إختار   صورة واحدة علي الأقل  ')
                return false;
            }

            return true;
        }


        $('form').on('submit', function (e) {

            e.preventDefault();

            var formData = new FormData(this);

            var form = $(this);
            form.parsley().validate();

            if (form.parsley().isValid() && validImages()){
            // if (form.parsley().isValid()  ){
                $('.loading').show();

                $.ajax({
                    type: 'POST',
                    url: $(this).attr('action'),
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        $('.loading').hide();
                        // $('form').trigger("reset");
                        console.log(data);

                        var shortCutFunction = 'success';
                        var msg = data.message;
                        var title = 'نجاح';
                        toastr.options = {
                            positionClass: 'toast-top-left',
                            onclick: null
                        };
                        var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
                        $toastlast = $toast;
                        setTimeout(function () {
                            window.location.href = data.url;
                        }, 2000);
                    },
                    error: function (data) {
                        $('.loading').hide();

                        errorVaildationMessage(data.responseJSON.error[0])
                    }
                });
            }else {
                $('.loading').hide();
            }
        });


        function errorVaildationMessage(message){
            var shortCutFunction = 'error';
            var msg = message;
            var title = 'فشل';
            toastr.options = {
                positionClass: 'toast-top-left',
                preventDuplicates: true,
                onclick: null
            };
            var $toast = toastr[shortCutFunction](msg, title);
            $toastlast = $toast;
        }

    </script>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.master')
@section('title', __('maincp.users_manager'))


@section('styles')



@endsection
@section('content')


    <form method="POST" action="{{ route('categories.update', $category->id) }}@if(request('type')  == 'subcategories' )?type=subcategories @endif" enctype="multipart/form-data"
          data-parsley-validate novalidate>
    {{ csrf_field() }}
    {{ method_field('PUT') }}


    <!-- Page-Title -->
        <div class="row">
            <div class="col-lg-12 ">
                <div class="btn-group pull-right m-t-15">
                    <button type="button" class="btn btn-custom  waves-effect waves-light"
                            onclick="window.history.back();return false;"> رجوع <span class="m-l-5"><i
                                    class="fa fa-reply"></i></span>
                    </button>
                </div>
                <h4 class="page-title">إسم {{$pageName}}</h4>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12 ">
                <div class="card-box">


                    <h4 class="header-title m-t-0 m-b-30">تعديل {{$pageName}}</h4>

                    <div class="row">

                        @if(request('type'))
                            <div class="col-xs-6">
                                <div class="form-group">
                                    <label for="userName">إسم القسم*</label>
                                    <select name="parentId"  class="form-control requiredFieldWithMaxLenght" required>
                                        <option value="" selected disabled="">إختر القسم</option>
                                        @foreach($cats as $value)
                                            <option value="{{ $value->id }}" @if($value->id == $category->parent_id) selected @endif>
                                                {{ $value->name }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        @endif



                            <div class="col-xs-6">
                                <div class="form-group">
                                    <label for="userName"> {{$pageName}}   باللغة العربية</label>
                                    <input type="text" name="name_ar"
                                           class="form-control requiredFieldWithMaxLenght"
                                           required value="{{$category->name_ar}}"
                                           placeholder="   باللغة العربية{{$pageName}}  ..."/>
                                    <p class="help-block" id="error_userName"></p>
                                    @if($errors->has('name_ar'))
                                        <p class="help-block">
                                            {{ $errors->first('name_ar') }}
                                        </p>
                                    @endif
                                </div>
                            </div>

                            <div class="col-xs-6">
                                <div class="form-group">
                                    <label for="userName"> {{$pageName}}   باللغة الإنجليزية</label>
                                    <input type="text" name="name_en" value="{{$category->name_en}}"
                                           class="form-control requiredFieldWithMaxLenght"
                                           required
                                           placeholder="   باللغة الإنجليزية {{$pageName}}  ..."/>
                                    <p class="help-block" id="error_userName"></p>
                                    @if($errors->has('name_en'))
                                        <p class="help-block">
                                            {{ $errors->first('name_en') }}
                                        </p>
                                    @endif
                                </div>
                            </div>

                            <div class="col-xs-6">
                                <div class="form-group">
                                    <label for="order_by"> الرقم التسلسلي لترتيب الأقسام   </label>
                                    <input type="number" name="order_by" value="{{$category->order_by}}"
                                           class="form-control number" min=0 oninput="validity.valid||(value='');"
                                           required   placeholder="الرقم التسلسلي لترتيب الأقسام"/>
                                </div>
                            </div>

                            <div class="col-xs-4">
                                <div class="form-group">
                                    <label for="usernames">صورة القسم *</label>
                                    <input type="hidden" value="{{ $category->getFirstMediaUrl() }}" name="oldImage"/>
                                    <input type="file" name="image" class="dropify" data-max-file-size="6M"
                                           data-default-file="{{ $category->getFirstMediaUrl() }}"/>
                                </div>
                            </div>
                        <!-- end col -->
                    </div>


                    <div class="form-group text-right m-t-20">
                        <button class="btn btn-warning waves-effect waves-light m-t-20" type="submit">
                            @lang('maincp.save_data')
                        </button>
                        <button onclick="window.history.back();return false;" type="reset"
                                class="btn btn-default waves-effect waves-light m-l-5 m-t-20">
                            @lang('maincp.disable')
                        </button>
                    </div>

                </div>
            </div><!-- end col -->


        </div>
        <!-- end row -->
    </form>

@endsection



@section('scripts')

    <script type="text/javascript"
            src="{{ request()->root() }}/public/assets/admin/js/validate-{{ config('app.locale') }}.js"></script>

    <script type="text/javascript">
        function validImages() {

            var images = $( "input[name='image']" ).val();
            var oldImage = $( "input[name='oldImage']" ).val();

            if ( (images === undefined || images === "" ) && (oldImage === undefined || oldImage === "")   ) {
                var shortCutFunction = 'error';
                var msg = 'من فضلك إختار   صورة واحدة علي الأقل  ';
                var title = 'نجاح';
                toastr.options = {
                    positionClass: 'toast-top-left',
                    preventDuplicates: true,
                    onclick: null
                };
                var $toast = toastr[shortCutFunction](msg, title);
                $toastlast = $toast;
                return false;
            }

            return true;
        }

        $('form').on('submit', function (e) {

            e.preventDefault();

            var formData = new FormData(this);

            var form = $(this);

            form.parsley().validate();

            if (form.parsley().isValid() && validImages()){
            // if (form.parsley().isValid() ){
                $('.loading').show();

                $.ajax({
                    type: 'POST',
                    url: $(this).attr('action'),
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {

                        $('.loading').hide();
                        messageDisplay( 'نجاح' , data.message);

                        setTimeout(function () {
                            window.location.href = data.url;
                        }, 2000);
                    },
                    error: function (data) {

                        $('.loading').hide();
                        errorMessageTostar('فشل',data.responseJSON.error[0]);
                    }
                });

            }


        });

        function messageDisplay($title, $message) {
            var shortCutFunction = 'success';
            var msg = $message;
            var title = $title;
            toastr.options = {
                positionClass: 'toast-top-left',
                onclick: null
            };
            var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
            $toastlast = $toast;
        }

        function errorMessageTostar($title, $message) {
            var shortCutFunction = 'error';
            var msg = $message;
            var title = $title;
            toastr.options = {
                positionClass: 'toast-top-left',
                onclick: null
            };
            var $toast = toastr[shortCutFunction](msg, title);
            $toastlast = $toast;
        }

    </script>
@endsection